config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :articles do
  	resources :comments
  end

  get 'welcome/index'

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article
  include Mongoid::Document
  field :title, type: String
  field :text, type: String

  validates :title, presence: true, length: { minimum: 5 }
  embeds_many :comments

  index({ starred: 1 })
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :commenter, type: String
  field :body, type: String
  
  embedded_in :article
end

app/models/person.rb
class Person
  include Mongoid::Document
  field :name, type: String
  field :street, type: String
  field :city, type: String
  field :state, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	http_basic_authenticate_with name: "admin", password: "1234", except: [:index, :show]

	def new
		@article = Article.new
	end

	def index
		@articles = Article.all
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	private
	def article_params
		params.require(:article).permit(:title, :text)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	http_basic_authenticate_with name: "admin", password: "1234", only: [:destroy]

	def create 
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)

		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy

		redirect_to article_path(@article)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :street, :city, :state)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Editing article</h1>

 
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= javascript_include_tag('test.js') %>

<h1>Listing articles</h1>

<table>
	<tr> 
		<th> Title </th>
		<th> Text </th>
	</tr>

	<% @articles.each do |article| %>
	<tr>
		<td> <%= article.title %> </td>
		<td> <%= article.text %> </td>
		<td> <%= link_to 'Show', article_path(article) %> </td>
		<td> <%= link_to 'Edit', edit_article_path(article) %> </td>
		<td> <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure' } %> </td>
	</tr> 
	<% end %>
</table>

<br>
<br>
<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1> New Post </h1>

<%= form_for :article, url: articles_path do |f| %>

	<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2> <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved: </h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
				<li> <%= msg %> </li>
				<% end %>
			</ul>		
		</div>
	<% end %>

	<p>
		<%= f.label :title %><br>
	   	<%= f.text_field :title %>
	</p>

	<p>
	    <%= f.label :text %><br>
	    <%= f.text_area :text %>
	</p>

	<p>
	    <%= f.submit %>
	</p>
<% end %>

<br> 

<%= link_to 'Show articles', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article </h1>

<p>
	<strong> Title: </strong>
	<%= @article.title %>
</p>

<p>
	<strong> Text: </strong>
	<%= @article.text %>
</p>

<br> 

<h2>Comments</h2>
	<% @article.comments.each do |comment| %>
		 <p>
		   	<strong>Commenter:</strong>
		   	<%= comment.commenter %>
		 </p>

		 <p>
		   	<strong>Comment:</strong>
		   	<%= comment.body %>
		 </p>

		 <p>
		   	<%= link_to 'Destroy comment', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
		 </p>
<% end %>

<h2>Add a comment:</h2>
	<%= form_for([@article, @article.comments.build]) do |f| %>
		<p>
		   <%= f.label :commenter %><br>
		   <%= f.text_field :commenter %>
		</p>
		<p>
		   <%= f.label :body %><br>
		   <%= f.text_area :body %>
		</p>
		<p>
		   <%= f.submit %>
		</p>
<% end %>

<%= link_to 'Back', articles_path %>
<%= link_to 'Edit', edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.street %></td>
        <td><%= person.city %></td>
        <td><%= person.state %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @person.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @person.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @person.state %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/welcome/index.html.erb
<h1>My second Playground</h1>
<h3>This is my playground site using Heroku + GitHub + MongoDB + Ruby on Rails</h3>
<h6> //>> Welcome#index</h6>
<br>

<h4>Click <a href="/people">here</a> and see the people!</h4>
<h4>Click <a href="/articles">here</a> and see my posts!</h4>

<br>
<h2>File Stack server</h2>
<script type="text/javascript" src="//api.filestackapi.com/filestack.js"></script>
<input type="filepicker" data-fp-apikey="A3cLtfPbbSWkSvc9VZKdAz" onchange="alert(event.fpfile.url)">